### ISSUE TITLE
Issues with 8 node cluster

### ISSUE THREAD

**Issue by roybalrm** [pokornyIt/cucm_performance_exporter#19]
I am getting this error if monitor_names has more than 4 servers.

evel=error msg="problem read OpenSession response. Status code: 500 Internal Server Error" func="main.(*perfClient).processRequest()" file="performance_client.go:55" operation="[OpenSession]" session=
time="2022-06-20 03:13:10.835" level=error msg="session request fail witk message response status is 500 Internal Server Error" func="main.(*perfMonService).OpenSession()" file="perfMonService.go:41" monitorNames="

**Comment by roybalrm** [comment]
Hi @pokornyIt thank you for your reply, I did see that in the logs but the strange thing is if I split my cluster nodes into 3 separate exporters I am able to connect to all my nodes successfully.

**Comment by pokornyIt** [comment]
Hello @roybalrm, I made a new version of this tool after a long time. This new version solves your problem with a number of servers. The root problem was in the request rate limit.
