### ISSUE TITLE
open server.yml not found

### ISSUE THREAD

**Issue by Resha777** [pokornyIt/cucm_performance_exporter#26]
I edited "config.yml" with my info but when i run the app i get this
./cucm_performance_exporter 
INFO[2024-03-14 10:28:54.850] application Initializing                      ApplicationName=cucm-perfmon-exporter Arch=386 CPUs=4 RuntimeVersion=go1.22.1
ERRO[2024-03-14 10:28:54.850] problem with configuration. Error: open server.yml: no such file or directory 
Program did not start due to configuration error! 

i'm not seeing a file called open server.yml

i tried to overwrite the config using flags but with the same issue

**Comment by pokornyIt** [comment]
Hi, if you run the program with the help option: `./cucm_performance_exporter -h`, you will see that the program standard expects a **server.yml** file in the working folder.

```text
usage: ___go_build_zqm_axl_importer_.exe [<flags>]

Flags:
  -h, --help            Show context-sensitive help (also try --help-long and
                        --help-man).
      --show            Show actual configuration and ends
      --config=cfg.yml  Configuration file default is "server.yml".
      --cli             Run only once and ends
      --version         Show application version.
```

For tests, you start: 
* `./cucm_performance_exporter --config=config.yml --show` - show actual configuration
* * `./cucm_performance_exporter --config=config.yml --cli` - run once not as a service
